services: 
  web: 
    build:
     context: app
     target: builder
    networks: 
      - selnet
    ports: 
      - '8000:8000'
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks: 
      - selnet

networks:
  selnet:
    external: true

volumes:
  mongodb_data: